name: Nightly E2E Tests Electron Pro Windows
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  e2eTestsElectronWin:
    name: Test TagSpaces Pro on Windows
    runs-on: windows-latest
    steps:
      - name: Checking out default branch
        uses: actions/checkout@v4
        with:
          ref: develop
          submodules: true
      - name: Checkout TestData
        uses: actions/checkout@v4
        with:
          repository: tagspaces/testdata
          path: tests/testdata
      - name: Configure NPM for TagSpaces Pro
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: '@tagspacespro'
      - name: Running npm install, prettier and type checks
        run: |
          npm install
          npm run prettier-check
          npm run type-check
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TSPNPMINSTALL }}
      - name: Run Unit tests
        run: npm run test-unit
      - name: Run Electron tests
        run: |
          npm run build-e2e
          npm run test-playwright-pro
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-artifacts
          path: |
            tests/test-reports/
            test-results/
            playwright-report/

#  e2eTestsElectronUbuntu:
#    name: E2E Ubuntu Electron
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checking out default branch
#        uses: actions/checkout@v4
#        with:
#          ref: develop
#          submodules: true
#      - name: Checkout TestData
#        uses: actions/checkout@v4
#        with:
#          repository: tagspaces/testdata
#          path: tests/testdata
#      - uses: actions/setup-node@v4
#        with:
#          node-version: '12.x'
#      - name: Running yarn install, prettier and type checks
#        run: |
#          yarn install --check-files --cache-folder .ycache
#          yarn prettier-check
#          yarn type-check
#      - name: Run Unit tests
#        run: yarn test-unit
#      - name: Run Electron tests
#        run: |
#          yarn install-ext
#          yarn build:main
#          yarn build-e2e
#          yarn test-playwright
#      - uses: actions/upload-artifact@v2
#        if: always()
#        with:
#          name: test-pages
#          path: tests/test-pages/

#  e2eTestsMinioUbuntu:
#    name: E2E Ubuntu Minio
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checking out default branch
#        uses: actions/checkout@v4
#        with:
#          ref: develop
#          submodules: true
#      - name: Checkout TagspacesPro
#        uses: actions/checkout@v4
#        with:
#          repository: tagspaces/tagspacespro
#          token: ${{ secrets.CHECKOUT_TSPRO  }}
#          path: extensions/tagspacespro
#      - name: Checkout TestData
#        uses: actions/checkout@v4
#        with:
#          repository: tagspaces/testdata
#          path: tests/testdata
#      - uses: actions/setup-node@v4
#        with:
#          node-version: '12.x'
#      - name: Running yarn install, prettier and type checks
#        run: |
#          yarn install --check-files --cache-folder .ycache
#          yarn prettier-check
#          yarn type-check
#      - name: Run Unit tests
#        run: yarn test-unit
#      - uses: suisei-cn/actions-download-file@v1
#        id: minio
#        name: Download the Minio
#        with:
#          url: 'https://dl.min.io/server/minio/release/linux-amd64/minio'
#          target: tests/bin/
#      - name: Make the Minio executable
#        run: chmod +x ./tests/bin/minio
#      - name: Run Electron tests
#        run: |
#          yarn install-ext
#          yarn build:main
#          yarn build-e2e
#          yarn test-e2e-electron-minio
#      - uses: actions/upload-artifact@v2
#        if: always()
#        with:
#          name: test-pages
#          path: tests/test-pages/
#
#  e2eTestsWebUbuntu:
#    name: E2E Ubuntu Web
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checking out default branch
#        uses: actions/checkout@v4
#        with:
#          ref: develop
#          submodules: true
#      - name: Checkout TagspacesPro
#        uses: actions/checkout@v4
#        with:
#          repository: tagspaces/tagspacespro
#          token: ${{ secrets.CHECKOUT_TSPRO  }}
#          path: extensions/tagspacespro
#      - name: Checkout TestData
#        uses: actions/checkout@v4
#        with:
#          repository: tagspaces/testdata
#          path: tests/testdata
#      - uses: actions/setup-node@v4
#        with:
#          node-version: '12.x'
#      - name: Running yarn install, prettier and type checks
#        run: |
#          yarn install --check-files --cache-folder .ycache
#          yarn prettier-check
#          yarn type-check
#      - name: Run Unit tests
#        run: yarn test-unit
#      - uses: suisei-cn/actions-download-file@v1
#        id: minio
#        name: Download the Minio.exe
#        with:
#          url: 'https://dl.min.io/server/minio/release/linux-amd64/minio'
#          target: tests/bin/
#      - name: Make the Minio executable
#        run: chmod +x ./tests/bin/minio
#      - name: Run Electron tests
#        run: |
#          yarn install-ext
#          yarn build:main
#          yarn build-e2e
#          yarn test-e2e-web
#      - uses: actions/upload-artifact@v2
#        if: always()
#        with:
#          name: test-reports
#          path: tests/test-reports/
