name: Manual Workflow Dispatch Trigger
on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Command to execute e2e tests default: npm run test-playwright-web-headless'
        required: true
        default: 'test-playwright-web-headless'

jobs:
  e2eTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out default branch
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Checkout TestData
        uses: actions/checkout@v4
        with:
          repository: tagspaces/testdata
          path: tests/testdata
      - name: Configure NPM for TagSpaces Pro
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          always-auth: true
          registry-url: https://npm.pkg.github.com/
          scope: '@tagspacespro'
      - name: Running npm install, prettier and type checks
        run: |
          npm install
          npm run generate-extensions
          npm run prettier-check
          npm run type-check
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TSPNPMINSTALL }}
      - name: Run Unit tests
        run: npm run test-unit
      - uses: suisei-cn/actions-download-file@v1.6.0
        id: minio
        name: Download Minio program
        with:
          # url: 'https://dl.min.io/server/minio/release/windows-amd64/minio.exe'
          url: 'https://dl.min.io/server/minio/release/linux-amd64/minio'
          target: tests/bin/
      - name: Make Minio executable
        run: chmod +x ./tests/bin/minio
      - name: Run Electron tests
        run: |
          npm run build-e2e
          npm run ${{ github.event.inputs.command }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-pages
          path: tests/test-pages/
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-artifacts
          path: |
            tests/test-pages/
            tests/test-reports/
